//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharlyEjemplo.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estatus
    {
        public int idStatus { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string nombre { get; set; }
    }
}
