//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharlyEjemplo.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int idUsuario { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> idEstatus { get; set; }
        public string loginUsuario { get; set; }
        public string passwordUsuario { get; set; }
        public string nombresUsuario { get; set; }
        public string apellidosUsuario { get; set; }
        public string emailUsuario { get; set; }
        public string telefonoUsuario { get; set; }
        public string celularUsuario { get; set; }
        public string departamentoUsuario { get; set; }
        public string lenguajeUsuario { get; set; }
        public Nullable<int> idRol { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
